# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryWebApp', '0005_auto_20161220_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
