# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryWebApp', '0006_auto_20161221_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='dateTime',
            field=models.DateTimeField(),
        ),
    ]
